micronaut:
  server:
    port: 8080
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${MICRONAUT_SECURITY_TOKEN_JWT}"

akhq:
  connections:
    my-cluster:
      properties:
        bootstrap.servers: "${KAFKA_BOOTSTRAP_SERVERS}"