micronaut:
  server:
    port: 8080
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "Jf8f7x9s2Kl0pQr3mNbVcXzA1wEyUiOoPaLkD5hG6tT7jR4eS8zC9bF2vM3nX0qW"

akhq:
  connections:
    my-cluster:
      properties:
        bootstrap.servers: "kafka.railway.internal:29092"