services:
  akhq:
    build: .
    container_name: akhq
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            my-cluster:
              properties:
                bootstrap.servers:${{ shared.KAFKA_BOOTSTRAP_SERVERS }}
      AKHQ_SERVER_PORT: 8080
    restart: unless-stopped
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge