services:
  akhq:
    build: .
    container_name: akhq
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${{ shared.KAFKA_BOOTSTRAP_SERVERS }}
    restart: unless-stopped
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge